# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
