# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20180228_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ValorCC',
            new_name='valorCC',
        ),
    ]
