# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='N\xfamero de Identificaci\xf3n')),
                ('nombreEmpresa', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre empresa')),
                ('nombreRepresentante', models.CharField(max_length=45, verbose_name='Nombre representante')),
                ('apellidoRepresentante', models.CharField(max_length=45, verbose_name='Apellido representante')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='+573041234567', max_length=128, verbose_name='Tel\xe9fono')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('ciudad', models.CharField(blank=True, max_length=25, null=True, verbose_name=' Ciudad')),
                ('direccion', models.CharField(blank=True, max_length=25, null=True, verbose_name='Direcci\xf3n')),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoCuenta', models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros'), ('recaudo', 'Recaudo')], max_length=25, null=True, verbose_name='Tipo de cuenta')),
                ('numeroCuenta', models.CharField(blank=True, max_length=15, null=True, verbose_name='N\xfamero de cuenta')),
            ],
        ),
    ]
